### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by sidboy55555** [Spicord/DiscordMOTD#2]
Hi,

It has been a long time since this addon was updated, but I would like to request a feature.
A custom status, I noticed the only choice was listening, watching and playing, but it would be nice to set a custom one like I did for my other bots:
![image](https://github.com/user-attachments/assets/1ecc5e0d-b1de-46fa-a9af-2ca87686b8ab)

**Comment by anvorgesa** [comment]
Hello! Thank you for your suggestion, I just implemented this, you can find the latest .sp file in this repo, take a look at the new config.yml in order to adapt your current one: [config.yml](https://github.com/Spicord/DiscordMOTD/blob/master/data/config.yml).

The changes made in this version includes the addition of 3 extra activity types (streaming, competing, & custom). And the ability to set the online status (dnd, idle, online, invisible).
